### ISSUE TITLE
Importing nodes with the same rdf:ID from different files

### ISSUE THREAD

**Issue by giantamoeba** [neo4j-labs/neosemantics#140]
I am trying to import multiple rdf files into neo4j as described [here](https://neo4j.com/docs/labs/nsmntx/current/import/)

My problem is that even though elements have the same rdf:ID they end up being imported as different neo4j nodes with different uris prefixed by the different file names like: `file:/x.xml#_00141f6c-69b1-4a1a-a83b-333d0bb9d586` and `file:/y.xml#_00141f6c-69b1-4a1a-a83b-333d0bb9d586`.

I have tried to use:

```
call semantics.addNamespacePrefix("local","file:/x.xml#")    
call semantics.addNamespacePrefix("local","file:/y.xml#")

```
before importing but to no avail. I have additionally tried to set `handleVocabUris: "MAP"` as an option for the import function.

Is there an import option that I am missing which allows these nodes to be unified? Is there generally an elegant way to reunify them after importing?

**Comment by jbarrasa** [comment]
Hi @giantamoeba, I have a suspicion what's going on here. In RDF, `rdf:ID` is a **relative** definition (uses the base namespace which will default to the file name if undefined) as opposed to `rdf:about`. Make sure you're using them correctly. Read [here](https://stackoverflow.com/questions/7118326/differences-between-rdfresource-rdfabout-and-rdfid).

Would it be possible for you to share a couple of the RDF files so we can try to understand/reproduce the issue? If not possible, you can always run a quick test and understand the full URIs in your RDF documents you can use the [RDF validation service](https://www.w3.org/RDF/Validator/rdfval) (only for RDF/XML) or this [RDF converter](http://www.easyrdf.org/converter) for all serialisations.

Hope this helps,

JB.

**Comment by giantamoeba** [comment]
I agree with you that `rdf:ID` is not the best way to go, unfortunately I don't have any control over this since I receive the rdf files as input. 

So my current workaround is to copy each file into a temp file before loading so that the prefixes are the same. Neo4j merges the nodes with the same uri into one, which is exactly what I need. This comes however with the penalty of not being able to parallelize the importing process. 

I wish I had more control over the way neosemantics uses for identifying nodes as "the same" so it updates an existing node instead of creating a new one.

**Comment by jbarrasa** [comment]
I'm afraid the only way in RDF to identify two nodes as being the same (other than using inferencing) is by using the same URI. So the model mapping capabilities would not help in this case and I'd be in principle reluctant to add non-standard interpretations of RDF in neosemantics.

But back to your solution, instead of copying your files into a temp file, you could also inject an `xml:base` attribute at the root of each document with the same vocabulary namespace as value (for instance: `xml:base="http://giantamoeba.com/myvoc/"`) and that should do the job. It would be a correct use of RDF and therefore neosemantics would parse it just as you expect.

Let me know your thoughts. 

Would help if I write a snippet to explain how to do it? What's your prefered programming language?

JB.

**Comment by giantamoeba** [comment]
The `xml:base` is indeed the way to go, thank you!
I am working in python with CGMES files and your plugin is of greate value.
