### ISSUE TITLE
Unable to import FIBO rdf files

### ISSUE THREAD

**Issue by deepakkochhar** [neo4j-labs/neosemantics#141]
Hi @jbarrasa 

I am trying to import a **FIBO rdf** file using **neosemantics** plugin but the triples are not being loaded (image below). 

**call semantics.importRDF("file://Corporations.rdf","RDF/XML")**

![image](https://user-images.githubusercontent.com/58933964/71571673-618fd800-2b01-11ea-8a0d-5bc3fd476f45.png)

But it works and the ontology is displayed when I am uploading the same file on **WebVOWL** http://www.visualdataweb.de/ 

![image](https://user-images.githubusercontent.com/58933964/71573305-35785500-2b09-11ea-8b0d-fbd68a65d52d.png)

The file can be accessed from https://drive.google.com/file/d/1mjrx67n5A3PPQwdun61vUFn-SXwJfHNx/view?usp=sharing

Can you please check the issue and kindly help me out with what I am doing wrong.

**Comment by jbarrasa** [comment]
Hi @dkdev12, sorry for the late response. 
The problem is with the url. You have to use `file://` followed by the absolute path to the file. Something like this in my case: 
`call semantics.importRDF("file:///Users/jb/Downloads/Corporations.rdf","RDF/XML", {})`

* notice the three slashes = `file://` + `/...`

The error message is not helping a lot in this case, I'll take a look at that. Thanks for raising it.

JB.

**Comment by JDRomano2** [comment]
Might I also suggest including in the documentation an example of using `importRDF` for local files on Windows? It took a fair number of tries to figure out the correct syntax. What ended up working was like follows (with the triple forward slash preceding the path and escaped backslashes within the path):

```
CALL semantics.importRDF("file:///D:\\Data\\some_rdf_file.rdf", "RDF/XML");
```

**Comment by jbarrasa** [comment]
Will do.  
Thanks!
JB

**Comment by jbarrasa** [comment]
Note on syntax for paths in windows has been added to the manual. 
Find it in the [import section](https://neo4j.com/docs/labs/nsmntx/current/import/#actual-rdf-import).
