### ISSUE TITLE
Neosemantics manual example 4.8 not working (not able to import rdf_type with instance data)

### ISSUE THREAD

**Issue by olijnykn** [neo4j-labs/neosemantics#159]
I'm using the neosemantics manual example in section 4.8 to learn how to import an ontology and its instance data into Neo4J using the neosemantics plugin. However, the example is not working as it is illustrated in the manual and I'm also not able to import my own ontology and instance data as is illustrated. Can you please help me establish why the manual's example is not working as illustrated?  

The neosemantics manual example can be found at this URL: https://neo4j.com/docs/labs/nsmntx/current/import/#classes-as-nodes

I'm using **Neo4J 4.0.4** with the **Neosemantics 4.0.0.1** plugin.

I set the constraint:
```
CREATE CONSTRAINT n10s_unique_uri ON (r:Resource)
ASSERT r.uri IS UNIQUE;
```
I set the config:
`CALL n10s.graphconfig.init({ keepLangTag: true, handleMultival: 'ARRAY'});`

I follow 4.8 instructions. 

I import the ontology: 
`call n10s.rdf.import.fetch("https://github.com/neo4j-labs/neosemantics/raw/3.5/docs/rdf/minionto.ttl","Turtle");`

![ontograph](https://user-images.githubusercontent.com/27958687/82815364-04594200-9e67-11ea-8b65-3bb5910de176.PNG)

The ontology import appears to work fine. The issue is with the next step (importing instance data).

I import the instance data:
```
call n10s.rdf.import.fetch("https://github.com/neo4j-labs/neosemantics/raw/3.5/docs/rdf/miniinstances.ttl","Turtle", {
  typesToLabels: false
});
```
The rdf_type instances do not show up as they do in the 4.8 example. 

![ontographplusinstances](https://user-images.githubusercontent.com/27958687/82815455-3d91b200-9e67-11ea-8be8-40bace0931cb.PNG)

As the screenshot shows, the rdf_type is not imported as it is with the example. The ns2_author is imported, but not rdf_type. 

How can I get the rdf_type to import and connect to the initial ontology class content as is illustrated in the example?

**Comment by jbarrasa** [comment]
hi @olijnykn, thanks for the detailed explanation!

Sorry, there are a number of inaccuracies in the manual, and the example you mention is one of them, so thanks for bringing it to our attention. We hope we'll have them fixed in the next release :) 

The basic reason is that the parameter that's used to determine whether types are to be stored in Neo4j as labels or as nodes has changed name and now it's called `handleRDFTypes`. This was done to accommodate a third option (both labels and nodes, based on a community request #143). In addition to that, these kinds of settings now go in the Graph Config rather than on every individual import method.

Here's the sequence of operations that you'll need to run to make it work:


```
// Set the graph config (you can use 'NODES' or 'LABELS_AND_NODES' to get both)
CALL n10s.graphconfig.init({ keepLangTag: true, handleMultival: 'ARRAY', handleRDFTypes: "LABELS_AND_NODES"});
```

```
// Import the ontology (notice the n10s.onto.* instead of the n10s.rdf.*)
call n10s.onto.import.fetch("https://github.com/neo4j-labs/neosemantics/raw/3.5/docs/rdf/minionto.ttl","Turtle");
```

```
// Import instance data
call n10s.rdf.import.fetch("https://github.com/neo4j-labs/neosemantics/raw/3.5/docs/rdf/miniinstances.ttl","Turtle")
```

Producing this graph:

![image](https://user-images.githubusercontent.com/9989143/82823241-1f47a880-9e9f-11ea-8c17-e2831ae45063.png)


Please let us know if this solved the problem.

Thanks for helping to make n10s better. Please, keep sharing your feedback here or in [the community site](https://community.neo4j.com/c/integrations/linked-data-rdf-ontology).

JB.

**Comment by olijnykn** [comment]
Thanks for the prompt response, JB. I followed your instructions, and everything is working fine. I'll make more use of the community site. By the way, very cool and much needed plugin!
