### ISSUE TITLE
Issue loading TTL Files + "IRI included an unencoded space: '32' [line 7]"

### ISSUE THREAD

**Issue by iamliamc** [neo4j-labs/neosemantics#197]
Hey Neosemantics, 

I am currently testing the plugin on a docker instance of Neo4j
```
docker run -d --publish=7474:7474 --publish=7687:7687 --volume=$HOME/neo4j/data:/data --env='NEO4JLABS_PLUGINS=["apoc", "n10s"]' --env=NEO4J_AUTH=none neo4j:latest
```

When I check `dbs.components()`:
```
│"Neo4j Kernel"│"4.1.2"  │"community"│
```

I've installed and run the constraints and graph configuration: 
```
CREATE CONSTRAINT n10s_unique_uri ON (r:Resource) ASSERT r.uri IS UNIQUE;
CALL n10s.graphconfig.init({handleVocabUris: 'IGNORE'});
```

I am able to load in an ontology file: 
```
CALL n10s.onto.import.fetch("https://brickschema.org/schema/1.1/Brick.ttl", "Turtle");
```

However when I call:
```
CALL n10s.rdf.import.fetch("https://github.com/BrickSchema/Brick/blob/master/examples/ebu3b_brick.ttl","Turtle");
```

I get: ```"IRI included an unencoded space: '32' [line 7]"```

I have tried to load in a number of turtle files from here all with the same issue: 
https://github.com/BrickSchema/Brick/tree/master/examples

The "test" RDF import call shown in the documentation works without issue: 
```
CALL n10s.rdf.import.fetch("https://github.com/neo4j-labs/neosemantics/raw/3.5/docs/rdf/nsmntx.ttl","Turtle");
```

I can't for the life of me figure out what is wrong about the turtle files listed above... perhaps this is better suited for a forum... 

Thanks for any insight
Liam

**Comment by iamliamc** [comment]
Let me know if you'd like me to take this issue down and focus my conversation here: 
https://community.neo4j.com/t/issue-with-neosemantics-v4-neo4j-v4-1-2-loading-in-turtle-files/30424

**Comment by jbarrasa** [comment]
Hi @iamliamc , try to load the raw file instead of the prettified html view. You can get the url of the raw RDF clicking on the `Raw` link on the Github page. Below is what it looks like for your file:
CALL `n10s.rdf.import.fetch("https://raw.githubusercontent.com/BrickSchema/Brick/master/examples/ebu3b_brick.ttl","Turtle")`

Now, this also throws an error because some uris are "invalid". The error message I get is this: 
`"Illegal percent encoding U+25 at index 73: http://ucsd.edu/building/ontology/ebu3b#EBU3B_RM_3xxx_3rd_FLR_SUPFLO_AVG_% [line 10979]"`

Here you can either choose to edit the RDF file and use valid urls or set the `verifyUriSyntax` param to `false` and neosemantics will just import them as they are. Here's what it would look like:

`CALL n10s.rdf.import.fetch("https://raw.githubusercontent.com/BrickSchema/Brick/master/examples/ebu3b_brick.ttl","Turtle", { verifyUriSyntax: false })`


Hope this helps,

JB.

**Comment by iamliamc** [comment]
Very very helpful thank you!

**Comment by mishraHemant123** [comment]
It worked for me thanks
