### ISSUE TITLE
AddMappingToSchema comes with unknown procedure output

### ISSUE THREAD

**Issue by majo72** [neo4j-labs/neosemantics#203]
I am trying to map my nodes to an exisitng schema (guided by quickgraph#7), but it will not work with the given procedures. 

Call:
```
call semantics.mapping.listSchemas("http://schema.org/") yield node as sch
call semantics.mapping.addMappingToSchema(sch,"Name","name") yield node as mapping
return mapping
```

The error result is: 
Unknown procedure output: `node` (line 1, column 72 (offset: 71))
"call semantics.mapping.listSchemas("http://schema.org/") yield node as sch"

When I use "prefix" instead of "node" (which I have observed with the call `semantics.mapping.addSchema("http://schema.org/","sch")`), the first line will work, but leave me with this error message: 
Unknown procedure output: `prefix` (line 2, column 78 (offset: 154))
"call semantics.mapping.addMappingToSchema(sch,"Name","name") yield prefix as mapping"

by using the procedure:
```
call semantics.mapping.listSchemas("http://schema.org/") yield prefix as sch
call semantics.mapping.addMappingToSchema(sch,"Name","name") yield prefix as mapping
return mapping
```

I have also tried the mapping lists (later in quickgraph#7), but gain the same results.
Could anyone PLEASE advice?

I am using Neo4J 3.5

**Comment by jbarrasa** [comment]
Hi @majo72 thanks for your interst in n10s!
Yes, the examples in the blog are sometimes outdated as I don't update them with new releases of n10s (it would be too much work!). The reference is the manual you can find [here](https://neo4j.com/docs/labs/nsmntx/current/). That's why I'd strongly recommend you to upgrade to 4.x. Also there were some breaking changes in when we released 4.x (see [migration notes](https://neo4j.com/labs/neosemantics/4.0/appendix_migration/)) 

But back to your issue. The syntax in 3.5 would be something like this:
```
call semantics.mapping.listSchemas("http://schema.org/") yield namespace 
call semantics.mapping.addMappingToSchema(namespace,"Name","name") yield schemaNs,schemaPrefix,schemaElement,elemName
return schemaNs,schemaPrefix,schemaElement,elemName
```

We no longer release it but if we dig in github history, here's a [link to the 3.5 version of the manual specifically the section on mappings](https://github.com/neo4j-labs/neosemantics/blob/3.5/docs/asciidoc/_mapping.adoc). You can find examples with the right syntax for the different mapping methods in 3.5.

Hope this helps. 

We'd love to hear about your experiment in the ['linkeddata/RDF/Ontologies' channel in the community site](https://community.neo4j.com/c/integrations/linked-data-rdf-ontology/162).

Cheers,

JB.

**Comment by majo72** [comment]
Dear jbarrasa! 
Thank you a lot for this rapid response. Really highly appreciated!

The syntax for 3.5 works. It is perfect to show some examples to my students and introduce them into providing linked data with a graph database with neo4j and neosemantics. I will move to 4.x as soon as possible, as well I will have a look at the channel and contribute when I have some material. 

Thanks again and keep up this wonderful work. Stay safe...
