### ISSUE TITLE
About losing properties on relationship after exporting RDF

### ISSUE THREAD

**Issue by MaseratiD** [neo4j-labs/neosemantics#216]
Hi, Jesus!

I recently used the n10s plugin and tried to export RDF files from the graph data in neo4j. However, the exported RDF file seems to discard the relationship properties in the property graph, and the node with multiple labels only has one label after exporting. (Note: my graph data is not imported from RDF. )

So I want to ask whether the current n10s does not support lossless export of attribute graph to RDF file? Or is it because I ignored some steps?

Thank you!

**Comment by jbarrasa** [comment]
Hi @MaseratiD,
RDF does not support properties in relationships so if you want to have them included you need to select one of the RDF-star serializations ([more on RDF-star here](https://w3c.github.io/rdf-star/)). 
n10s supports RDF-star, all you need to do is add the parameter `format` set to `"Turtle*"` and you should get the relationship properties too.

Regarding the multi labelled nodes, it should work, so if you're seeing an unexpected behavior please share a fragment of your graph and steps to reproduce it.

Thanks.

JB.

**Comment by MaseratiD** [comment]
Thank you a lot for this rapid response!

If I want to try to export RDF as reification or singleton property, is there any way?  If these methods are not supported, I would like to ask the reason why n10s does not support the above form of export. Is it because it will destroy the original structure of the graph?

Thank you!

**Comment by jbarrasa** [comment]
Let me turn the question around. Why would you want to use reification and singleton when there is a much simpler mechanism (RDF-star) that is equally expressive?

My honest answer to why do we not support them would be that we've not seen any interest in them from the community. This is actually the very first time we are asked about them :)

Cheers,

JB.

**Comment by MaseratiD** [comment]
Thank you very much for your reply.

Indeed, RDF star is much simpler than other methods. But using reification instead of RDF star is because virtuoso doesn't support it. Now I find that Jena can support RDF star very well, and I can use the exported RDF on Jena.

Finally, thank you for your patient reply. I have learned a lot from it :)

**Comment by matentzn** [comment]
I have not looked at neosemantics in 3 years, and now that I do I am amazed at how great it has become. I am 100% in OWL-land, but am now looking to using it now regularly for certain graph queries that are too hard in sparql. However I would also like to throw my head in the ring regarding re-ified triples. We make heavy use of these in OBO for provenance (for example, on subclass of axioms to denote the source of the classification). RDF-star is no option for us because of the uniqueness constraint on annotated triples (worst design decision, very unfortunate). (A subClass B [claimedBy: paper1, inPage: 3], A subClass B [claimedBy: paper2, inPage: 5] is totally valid RDF and not expressible in RDF-star).

So, here it is: to pick up the biomedical community which works a lot with evidence and provenance on graphs, I would like to request to reconsider reading simple annotation assertions on relations as edge properties. Thank you :)
