### ISSUE TITLE
SHACL shapes don't work with handleVocabUris: "IGNORE"

### ISSUE THREAD

**Issue by Kubera2017** [neo4j-labs/neosemantics#229]
I use neosemantics for Neo4j native LPG validation (not RDF).
Previously (I remember version 4.2) I found that I need to init config with
call n10s.graphconfig.init({handleVocabUris: "IGNORE"})
to get it work with examples from docs.
But now it doesn't work and I get strange output for listShapes()

My steps:
1) CALL n10s.graphconfig.init({handleVocabUris: "IGNORE"})
2) CALL n10s.validation.shacl.import.inline('
@prefix ex: <http://example/> .
@prefix neo4j: <neo4j://voc#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .

ex:PersonShape
	a sh:NodeShape ;
	sh:targetClass neo4j:Person ;    # Applies to all Person nodes in Neo4j
	sh:property [
		sh:path neo4j:name ;           # constrains the values of neo4j:name
		sh:maxCount 1 ;                # cardinality
		sh:datatype xsd:string ;       # data type
		sh:pattern "^\w[\s\w\.]*$" ;   # string data format
	] ;
	sh:property [
		sh:path neo4j:ACTED_IN ;       # constrains the values of neo4j:ACTED_IN
		sh:class neo4j:Movie ;         # range
		sh:nodeKind sh:IRI ;           # type of property
		sh:severity sh:Warning ;
	] ;
	sh:closed true ;
	sh:ignoredProperties ( neo4j:born neo4j:DIRECTED neo4j:FOLLOWS neo4j:REVIEWED neo4j:PRODUCED neo4j:WROTE ) .

','Turtle')

Then I got the output and transaction validation doesn't work unfortunately:
![chrome_Q6QzFLC0Ou](https://user-images.githubusercontent.com/29781060/126769681-c90e5f39-f929-4ac4-88cc-0de479293764.png)

**Comment by Kubera2017** [comment]
@palandlom I remember it worked in this April (so working version should be 4.2.0.0) if it helps

**Comment by palandlom** [comment]
> @palandlom I remember it worked in this April (so working version should be 4.2.0.0) if it helps

Thanks for reply) But  4.2.0.0 has this [issue](https://github.com/neo4j-labs/neosemantics/issues/211) which is critical in my case.

**Comment by jbarrasa** [comment]
Hi!

There is an explanation for this behavior (and it should have been properly documented, apologies for having failed at that).

When working in `handleVocabUris: "IGNORE"` mode or with a native property graph (not resulting of importing RDF), then namespaces don't make much sense. That's why in previous versions, we just ignored the namespaces used in the SHACL definitions and used to keep the local names for types, properties, etc. That made it completely irrelevant the fact that one namespace or another was used for the schema elements. However, it felt wrong that shapes defined on different uris could end up being merged into the same type. 
Let me give an example: If you defined a shape on `sh:targetClass voc1:Person` and another shape on `sh:targetClass voc2:Person` they would both end up being applied to nodes of type `Person` because we were literally stripping out the namespace part (tame behavior would apply to properties, etc).

In the latest version, we have enforced the use of the default neo4j schema namespace: `neo4j://graph.schema#`. Now when in `handleVocabUris: "IGNORE"` mode or with native property graphs, shapes need to be defined on schema elements in this default namespace: `neo4j://graph.schema#`. Anything different from that will be ignored, which is what you are experimenting. I hope that makes sense. 

Back to your example, if you replace the prefix definition `@Prefix <neo4j: neo4j://voc#> .` with `@Prefix <neo4j://graph.schema#> .` everything should work as expected.


I hope this helps, thanks for reporting it, and apologies again for the inconvenience.

Closing the issue, feel free to reopen if needed.

**Comment by milnerm** [comment]
Documentation is still not updated at 
https://neo4j.com/labs/neosemantics/4.0/validation/

to
<neo4j://graph.schema#>

**Comment by NikolaiDrigalNTNU** [comment]
Documentation still not updated as of 2026.
