### ISSUE TITLE
Feature Request:  better linkage between RDF instance data and a corresponding ontology

### ISSUE THREAD

**Issue by mdw00d** [neo4j-labs/neosemantics#78]
Currently, the method semantics.importRDF supports a mechanism whereby rdf:type values are  translated to neo4j property labels.  However, it is difficult to map the rdf type of an imported RDF resource to the corresponding class in an ontology imported using semantics.liteOntoImport.   An example of where one might want this capability would be if one wanted to query the graph to find all nodes that were a subclass of some superclass in the ontology.

Cypher does not support queries where variables are used to represent labels.  Although one can enumerate the labels associated with a node using the labels() function, that is a bit cumbersome.

It would be useful to have the ability to specify that the rdf:type value is translated to a node property, such as RDFType, where the value of the property is the rdf:type, which can then be readily used to reference corresponding nodes in the ontology.

I have implemented this change.  In my implementation, I associated a new property with ontological nodes that had the value of the qualified name of the node's URI; I then modified the importRDF method so that it supported a new, optional feature similar to typesToLabel except that the type is added as a property value, again using the qualified name for notational convenience.  (I leveraged the NamespacePrefixDefinition node so that semantics.liteOntoImport could use the qualified namespaces).

If there's a better way to establish this linkage, I would be interested in knowing what it is.

**Comment by jbarrasa** [comment]
Hi Mark, you bring up a great point that I was also thinking needed to improve in nsmntx. 

Let me see if I've understood it right. You're suggesting adding a property that holds the types of a given resource. 

So this set of triples:
```
<http://mydataset.com/ind#001> rdf:type <http://myvocabulary#Thing>
<http://mydataset.com/ind#001> rdf:type <http://myvocabulary#Person>
<http://mydataset.com/ind#001> rdf:type <http://myvocabulary#Woman>
<http://mydataset.com/ind#001> <http://myvocabulary#name> "Joana Smith"
```
Would produce something like this:
```
CREATE (:Resource { uri: <http://mydataset.com/ind#001>, 
                    name: "Joana Smith" 
                    RDFType: [ "http://myvocabulary#Thing", "http://myvocabulary#Person", "http://myvocabulary#Woman"] })
```
(or a shortened version of the uris for the types) instead of the label representation or the separate node representation that you get when you set `typesToLabels: false`.

And the reason for that is to be able to link it to an ontology imported via `LiteOntoImport`. For example, if I want to get the classes of an individual, I'd be able to do this:

```
MATCH (:Resource { uri: "http://mydataset.com/ind#001"})
MATCH (class:Class) WHERE class.uri IN individual.RDFType
RETURN class
```
 
Is this what you're trying to achieve?


Cheers,

JB

**Comment by mdw00d** [comment]
Yes, that is what I had in mind, and the problem I was trying to solve.

 

Since I am accustomed to graphs having a single rdf:type assertion for a given resource, I was thinking (and implemented) something akin to:

 

CREATE (:Resource { uri: <http://mydataset.com/ind#001>, 
                    name: "Joana Smith" 
                    RDFType: "http://myvocabulary#Woman" })

 

with the expectation that any super classes in a class hierarchy would be inferred, but that is not a general solution; your solution should cover the general case.  

 

If all the classes of an individual were not explicitly expressed with rdf:type statements, then a micro inferencer could compute those classes for a given resource by returning the union of the set of classes denoted by values for the RDFType (as you show) with the set of all classes for superclasses of those classes.   

 

Thanks.

**Comment by jbarrasa** [comment]
I guess there are cases where an individual can be grouped in multiple categories (have multiple classes) without them being all inferrable via `subClassOf` taxonomy. Think for example of a classification by type of user and by geography, something like:

```
<http://mydataset.com/ind#001> rdf:type <http://myvocabulary#PremiumUser>
<http://mydataset.com/ind#001> rdf:type <http://myvocabulary#EMEAUser>
<http://mydataset.com/ind#002> rdf:type <http://myvocabulary#PremiumUser>
<http://mydataset.com/ind#002> rdf:type <http://myvocabulary#AMERUser>
<http://mydataset.com/ind#003> rdf:type <http://myvocabulary#BasicUser>
<http://mydataset.com/ind#003> rdf:type <http://myvocabulary#APACUser>
```

What I mean by that is that the `RDFType` property is genuinely multivalued in the general case independently of what additional types could be derived via inference.

In light of that, I don't really see a huge difference between the kind of query you could write with a multivalued property (the one I showed in my previous comment) and the one you have to write with the label-based implementation. The syntax is practically identical:

```
MATCH (individual:Resource { uri: "http://mydataset.com/ind#001"})
MATCH (class:Class) WHERE class.uri IN labels(individual)
RETURN class
```
Would you agree with that? 

This makes me think that in order to get a better linkage between instance data and ontology we'll have to explore things like using `typesToLabels: false` combined with importing the ontology (as plain RDF via `importRDF`, or alternatively via `liteOntoImport`).


JB.

**Comment by mdw00d** [comment]
My only question on that approach is that it assumes all labels correspond to rdf:type values.   One might want to have labels for other purposes.  For example, the RDF importer now associates the label Resource with nodes corresponding to RDF resources, and applications might wish to associate other labels with nodes.  While such resources could be filtered out (perhaps by adding a string suffix/prefix to the ones that are types, perhaps hard coding the knowledge into the application) and or otherwise ignored (because they don't match a type in the ontology), it seems like separating out the rdf:type values by themselves could be cleaner.

There's probably a performance impact one way or the other too, with respect to neo4j, but I am too much of a neo4j neophyte to know the trade-offs.

**Comment by mdw00d** [comment]
I have submitted a revised feature request this is perhaps a bit more thought through than this.
[143](https://github.com/neo4j-labs/neosemantics/issues/143)
